src/models/channels.py
from src.models.base import BaseModel
from src.exs import db


class Channel(BaseModel):
    __tablename__ = "channels"

    name = db.Column(db.String)
    id = db.Column(db.Integer, primary_key=True)
    channel_admin = db.Column(db.Integer)

src/views/channel/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField,SubmitField
from wtforms.validators import DataRequired


class Channel_Form(FlaskForm):
    name = StringField("Name",validators=[DataRequired()])
    submit = SubmitField("Submit")

src/views/channel/routes.py
from flask import render_template, Blueprint, redirect, url_for, request

from src.models import Channel, Message
from src.views.channel.forms import Channel_Form

from flask_login import current_user


from src.views.main.forms import Message_Form

channel_blueprint = Blueprint("channel", __name__)


@channel_blueprint.route("/channel", methods=["GET"])
def channel():
    all_channels = Channel.query.all()
    return render_template("channels/channel.html", channels=all_channels)


@channel_blueprint.route("/channel_chat/<int:channel_id>", methods=['POST', 'GET'])
def channel_chat(channel_id):
    current_channel = Channel.query.filter_by(id=channel_id).first()
    channel_messages = Message.query.filter_by(channel_id=channel_id)
    channel_admin = current_channel.channel_admin
    form = Message_Form()
    if request.method == "POST" and form.validate_on_submit():
        if current_user.is_authenticated:
            new_message = Message()
            new_message.channel_id = channel_id
            form.name.data = current_user.name
            form.populate_obj(new_message)
            new_message.create()
        else:
            return redirect(url_for("auth.login"))

        return redirect(url_for("channel.channel_chat", channel_id=channel_id))

    return render_template("channels/channel_chat.html", messages=channel_messages, form=form,
                           admin=channel_admin)


@channel_blueprint.route("/create_channel",methods=["GET","POST"])
def create_channel():
    form = Channel_Form()
    if request.method == "POST" and form.validate_on_submit():
        new_channel = Channel()
        new_channel.channel_admin = current_user.id
        form.populate_obj(new_channel)
        new_channel.create()
        return redirect(url_for("channel.channel"))

    return render_template("channels/create_channel.html",form = form)


@channel_blueprint.route("/delete/<int:message_id>", methods=['POST'])
def delete_message(message_id):
    message_to_delete = Message.query.get_or_404(message_id)
    message_to_delete.delete()

    return redirect(url_for("channel.channel_chat",channel_id=message_to_delete.channel_id))


@channel_blueprint.route("/delete_channel/<int:channel_id>",methods=["POST"])
def delete_channel(channel_id):
    channel_to_delete = Channel.query.get_or_404(channel_id)
    channel_to_delete.delete()

    return redirect(url_for("channel.channel"))

src/templates/channels/channel.html
{% include "layouts/base.html" %}

{% block content %}

<p><h1>All Channel list</h1></p>
{%for channel in channels%}

{%if current_user.id == channel.channel_admin%}
<form method="post" action="{{ url_for('channel.channel_chat',channel_id=channel.id) }}" style="display: inline;">
                <button type="submit" class="btn btn-success">{{channel.name}}</button>--
            </form>
<form method="post" action="{{ url_for('channel.delete_channel',channel_id=channel.id) }}" style="display: inline;">
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
<br>
{%else%}
<form method="post" action="{{ url_for('channel.channel_chat',channel_id=channel.id) }}" style="display: inline;">
                <button type="submit" class="btn btn-success">{{channel.name}}</button>
            </form>
<br>
{%endif%}

<br>

<br>
{% endfor %}

<br>

{%if current_user.is_authenticated == False%}
<form method="post" action="{{ url_for('auth.login',) }}" style="display: inline;">
                <button type="submit" class="btn btn-dark">Create</button>
            </form>
{%else%}
<form method="post" action="{{ url_for('channel.create_channel',) }}" style="display: inline;">
                <button type="submit" class="btn btn-dark">Create</button>
            </form>


{%endif%}



{% endblock %}

src/templates/channels/channel_chat.html
{% include "layouts/base.html" %}


{% block content %}


    {%for message in messages%}
<div>
    <p>Name:{{message.name}}</p>

    <p> Message: {{message.message}}</p>
    <br>

    {%if current_user.id == admin%}
    <form method="post" action="{{ url_for('channel.delete_message', message_id=message.id) }}" style="display: inline;">
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
    {%elif current_user.name == message.name%}
    <form method="post" action="{{ url_for('channel.delete_message', message_id=message.id) }}" style="display: inline;">
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>
    {%else%}
        <form method="post" action="{{ url_for('channel.delete_message', message_id=message.id) }}" style="display: inline;">
                <button type="submit" class="btn btn-danger" DISABLED>Delete</button>
            </form>
    {%endif%}


</div>
<br>
<br>
{%endfor%}


{% if messages == [] and current_user.is_authenticated == False %}
<p>Log in to Start Chatting!</p>
{%endif%}

{%if current_user.is_authenticated == False%}
<p>Log in to Start Chatting!</p>
<form method="post" action="{{ url_for('auth.login',) }}" style="display: inline;">
                <button type="submit" class="btn btn-success">Login</button>
            </form>
{%else%}
<form method="post">
 <br>
     {{ form.hidden_tag() }}
    {{form.message(class="form-control", placeholder=form.message.label.text)}}
    <br>
    {{form.submit(class="btn btn-primary mt2")}}
</form>
{%endif%}
{% endblock %}

src/templates/channels/create_channel.html
{% include "layouts/base.html" %}

{% block content %}

<form method="post">
   {{form.hidden_tag()}}
 <br>
    {{form.name(class="form-control", placeholder=form.name.label.text)}}
    <br>
    <br>
    {{form.submit(class="btn btn-primary mt2")}}
   </form>

{% endblock %}