src/models/base.py
from src.exs import db


class BaseModel(db.Model):

    __abstract__ = True

    def create(self, commit=True, flush=False):
        db.session.add(self)

        if commit:
            self.save()

        if flush:
            self.delete()

    def save(self):
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

src/views/offer/routes.py
from flask import render_template, Blueprint, redirect, url_for, request

from src.views.offer.api import games_list, game_name

offer_blueprint = Blueprint("offer", __name__)


@offer_blueprint.route("/offers")
def offer():
    all_games = games_list()
    all_games_name = game_name(all_games)
    test_games = [381210,2446550,1551360,2427700,582010,1621690,961200]
    test_name = ["Dead_by_Daylight","STAR_WARS_Battlefront_Classic_Collection","Forza_Horizon_5","Backpack_Battles","Monster_Hunter_World","Core_Keeper","Predecessor"]
    print(all_games)
    print(all_games_name)
    return render_template("offers/offers.html", games_list=test_games, game_name=test_name)

src/templates/layouts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="">SobaCook</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{{ url_for('main.about') }}">About Us</a>

        {%if current_user.is_authenticated == False%}
        {%else%}
        <a class="nav-link" href="{{ url_for('channel.channel')}}">Channel</a>
        <a class="nav-link" href="{{ url_for('offer.offer')}}">Offers</a>
        <a class="nav-link" href="{{ url_for('trade.create_trade') }}">Trades</a>
        <a class="nav-link" href="{{ url_for('sell.market') }}">Market</a>
        <a class="nav-link" href="{{ url_for('auth.profile') }}">Profile</a>
        {%endif%}
        {%if current_user.is_authenticated%}
        <a class="nav-link" href="{{ url_for('auth.login') }}">Log out</a>
        {%else%}
        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
        <a class="nav-link" href="{{ url_for('auth.login') }}">Log in</a>
        {%endif%}

      </div>
    </div>
  </div>
</nav>

{% block content%}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>

</body>
</html>